config/routes.rb
ChildMonitor::Application.routes.draw do
  
  resources :user_sessions
  resources :users
  
  resources :kibera_children do
    resources :child_photos
  end
  
  resources :imports
  resources :exports
  
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout 

  root :to => 'kibera_children#index'

end

app/controllers/kibera_children_controller.rb
class KiberaChildrenController < ApplicationController
  before_filter :format_dates, :only => [:create, :update]
  
  # GET /kibera_children
  # GET /kibera_children.json
  def index
    if params[:per_page]
      session[:per_page] = params[:per_page].to_i
    end

    if params[:grade]
      session[:grade] = (params[:grade].downcase == "all") ? nil : params[:grade]
    end

    if params[:search]
      session[:search] = (params[:search].empty?) ? nil : params[:search]
      session[:per_page] = nil
      session[:grade] = nil
    end

    @kibera_children = KiberaChild.find_children(session[:search], session[:grade]).page(params[:page]).per_page(session[:per_page] || 25)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kibera_children }
    end
  end

  # GET /kibera_children/1
  # GET /kibera_children/1.json
  def show
    @kibera_child = KiberaChild.find(params[:id])
    @aws_photos = @kibera_child.aws_photos
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @kibera_child }
    end
  end

  # GET /kibera_children/new
  # GET /kibera_children/new.json
  def new
    @kibera_child = KiberaChild.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @kibera_child }
    end
  end

  # GET /kibera_children/1/edit
  def edit
    @kibera_child = KiberaChild.find(params[:id])
    @aws_photos = @kibera_child.aws_photos
  end

  # POST /kibera_children
  # POST /kibera_children.json
  def create
    @kibera_child = KiberaChild.new(params[:kibera_child])
    @kibera_child.first_name.strip!
    @kibera_child.last_name.strip!
    
    respond_to do |format|
      if @kibera_child.save
        format.html { redirect_to @kibera_child, :notice => @kibera_child.first_name + ' ' +  @kibera_child.last_name + ' was successfully created.' }
        format.json { render :json => @kibera_child, :status => :created, :location => @kibera_child }
      else
        format.html { render :action => "new" }
        format.json { render :json => @kibera_child.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kibera_children/1
  # PUT /kibera_children/1.json
  def update
    @kibera_child = KiberaChild.find(params[:id])
    params[:kibera_child][:first_name].strip!
    params[:kibera_child][:last_name].strip!

    respond_to do |format|
      if @kibera_child.update_attributes(params[:kibera_child])
        format.html { redirect_to @kibera_child, :notice => @kibera_child.first_name + ' ' +  @kibera_child.last_name + ' was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @kibera_child.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kibera_children/1
  # DELETE /kibera_children/1.json
  def destroy
    @kibera_child = KiberaChild.find(params[:id])
    @kibera_child.destroy

    respond_to do |format|
      format.html { redirect_to kibera_children_url }
      format.json { head :ok }
    end
  end
  
  private 
  
  def format_dates
    params[:kibera_child][:birth_date] = (params[:kibera_child][:birth_date] && params[:kibera_child][:birth_date].length > 0) ? Date.strptime(params[:kibera_child][:birth_date], '%m/%d/%Y') : nil
    params[:kibera_child][:assessment_documentation_date] = (params[:kibera_child][:assessment_documentation_date] && params[:kibera_child][:assessment_documentation_date].length > 0) ? Date.strptime(params[:kibera_child][:assessment_documentation_date], '%m/%d/%Y') : nil
    params[:kibera_child][:tb_date] = (params[:kibera_child][:tb_date] && params[:kibera_child][:tb_date].length > 0) ? Date.strptime(params[:kibera_child][:tb_date], '%m/%d/%Y') : nil
    params[:kibera_child][:typhoid_date] = (params[:kibera_child][:typhoid_date] && params[:kibera_child][:typhoid_date].length > 0) ? Date.strptime(params[:kibera_child][:typhoid_date], '%m/%d/%Y') : nil
    params[:kibera_child][:malaria_date] = (params[:kibera_child][:malaria_date] && params[:kibera_child][:malaria_date].length > 0) ? Date.strptime(params[:kibera_child][:malaria_date], '%m/%d/%Y') : nil
    params[:kibera_child][:hygenall_products_distribution_date] = (params[:kibera_child][:hygenall_products_distribution_date] && params[:kibera_child][:hygenall_products_distribution_date].length > 0) ? Date.strptime(params[:kibera_child][:hygenall_products_distribution_date], '%m/%d/%Y') : nil
    params[:kibera_child][:physical_examination_date] = (params[:kibera_child][:physical_examination_date] && params[:kibera_child][:physical_examination_date].length > 0) ? Date.strptime(params[:kibera_child][:physical_examination_date], '%m/%d/%Y') : nil
    params[:kibera_child][:menstrual_products_distribution_date] = (params[:kibera_child][:menstrual_products_distribution_date] && params[:kibera_child][:menstrual_products_distribution_date].length > 0) ? Date.strptime(params[:kibera_child][:menstrual_products_distribution_date], '%m/%d/%Y') : nil
  end
  
end

app/helpers/kibera_children_helper.rb
module KiberaChildrenHelper
end

app/views/kibera_children/edit.html.erb
<%= render :partial => 'form' %>

app/views/kibera_children/index.html.erb
<div class="container">
	<% if KiberaChild.count > 0 %>
		<div class="row">
			<div class="span12">
		    	<div class="child-list-nav">
					<ul class="nav nav-pills">
						<li>
							<%= form_tag kibera_children_path, :method => 'get', :class => 'navbar-form pull-left' do %>
								<%= text_field_tag :search, session[:search], :class => 'search-query', :placeholder => "Search..." %>
								<%= submit_tag 'Search', :name => nil, :class => 'btn' %>
							<% end %>
						</li>
						<li class="dropdown">
						    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
						          Actions
						          <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu">
								<li><%= link_to 'Add New Child', new_kibera_child_path %></li>
								<li class="divider"></li>
								<li>
									<%= link_to exports_path, :class => 'export-action' do %>
										<%= image_tag("excel.png", :border => 0) %><span>Export to Excel</span>
									<% end %>
								</li>
						    </ul>
						</li>
					  	<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						          Per Page
						          <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu">
								<li><%= link_to '25', kibera_children_path(:per_page => 25) unless session[:per_page].nil? || session[:per_page] == 25 %></li>
								<li><%= link_to '50', kibera_children_path(:per_page => 50) unless session[:per_page] == 50 %></li>
								<li><%= link_to '100', kibera_children_path(:per_page => 100) unless session[:per_page] == 100 %></li>
						    </ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						          By Class
						          <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu">
								<li><%= link_to 'All', kibera_children_path(:grade => 'all') if session[:grade] %></li>
								<li><%= link_to 'Pre-Unit', kibera_children_path(:grade => 'pre') unless session[:grade] && session[:grade].downcase == 'pre' %></li>
								<li><%= link_to 'Class 1', kibera_children_path(:grade => '1') unless session[:grade] && session[:grade] == '1' %></li>
								<li><%= link_to 'Class 2', kibera_children_path(:grade => '2') unless session[:grade] && session[:grade] == '2' %></li>
								<li><%= link_to 'Class 3', kibera_children_path(:grade => '3') unless session[:grade] && session[:grade] == '3' %></li>
								<li><%= link_to 'Class 4', kibera_children_path(:grade => '4') unless session[:grade] && session[:grade] == '4' %></li>
								<li><%= link_to 'Class 5', kibera_children_path(:grade => '4') unless session[:grade] && session[:grade] == '5' %></li>
								<li><%= link_to 'Class 6', kibera_children_path(:grade => '4') unless session[:grade] && session[:grade] == '6' %></li>
								<li><%= link_to 'Class 7', kibera_children_path(:grade => '4') unless session[:grade] && session[:grade] == '7' %></li>
								<li><%= link_to 'Class 8', kibera_children_path(:grade => '4') unless session[:grade] && session[:grade] == '8' %></li>
						    </ul>
					  	</li>
					</ul>
				</div>
			</div>
		</div>
	
		<% if @kibera_children.count > 0 %>
			<div class="row">
				<div class="span12 child-list-results">
					<div class="row">
						<div class="span3">
							<%= page_entries_info @kibera_children, :model => 'child' %>
						</div>
						<div class="offset5 span4 right-text">
							<%= will_paginate @kibera_children, :class => "pagination1" %>
						</div>
					</div>
				</div>
			</div>
	
			<div class="row">
				<div class="span12">
					<table class="table table-striped">
						<thead>
						    <tr>
							  <th>Child Name</th>
							  <th>Class</th>
						      <th>Actions</th>
						    </tr>
						</thead>
					  <tbody>
					    <% @kibera_children.each do |kibera_child| %>
					      <tr>
					        <td style="white-space:nowrap;"><%= link_to kibera_child.first_name + ' ' + kibera_child.last_name, kibera_child_path(kibera_child) %></td>
							<td style="width:99%;"><%= kibera_child.grade %></td>
					        <td style="white-space:nowrap;">
					          <%= link_to content_tag('i', '', :class => 'icon-pencil'), edit_kibera_child_path(kibera_child), :class => 'btn btn-mini', :title => "Edit" %>
					          <%= link_to content_tag('i', '', :class => 'icon-trash icon-white'), kibera_child_path(kibera_child), :method => :delete, :class => 'btn btn-mini btn-danger delete-confirm', :title => "Delete" %>
					        </td>
					      </tr>
					    <% end %>
					  </tbody>
					</table>
				</div>
			</div>
		<% else %>
			<div class="row">
				<div class="span12">
					<p>No children found.</p>
				</div>
			</div>
		<% end %>
	
	<% else %>
		<div class="row">
			<div class="span12">
				<p>There are no children entered at this time. Would you like to <%= link_to 'add a child', new_kibera_child_path %>?</p>
			</div>
		</div>
	<% end %>
</div>

app/views/kibera_children/new.html.erb
<%= render :partial => 'form' %>