config/routes.rb
ChildMonitor::Application.routes.draw do
  
  resources :user_sessions
  resources :users
  
  resources :kibera_children do
    resources :child_photos
  end
  
  resources :imports
  resources :exports
  
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout 

  root :to => 'kibera_children#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "NHI Kibera" %></title>
	<!--[if lt IE 9]>
	    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	  <![endif]-->
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<%= yield(:head) %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
	   	<div class="navbar-inner">
	      	<div class="container">
				<%= link_to "/", :class => 'brand' do %>
				    <%= image_tag("new-hope-logo.jpg", :border=>0) %> 
					<span>
				    	<span class="new-hope-text">New Hope</span><br/>
				    	Initiative
					</span>
				<% end %>
				<ul class="nav">
					<li><%= link_to "Home", kibera_children_path %></li>
					<% if current_user && current_user.is_admin? %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Admin
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Manage Users', users_path %></li>
								<li><%= link_to 'Add User', new_user_path %></li>
								<li class="divider"></li>
								<li><%= link_to "Import From CSV", new_import_path %></li>
							</ul>
						</li>
					<% end %>
	        	</ul>
				<% if current_user %>
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%= current_user.first_name + ' ' + current_user.last_name %>
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Edit Profile", edit_user_path(:current) %></li>
								<li class="divider"></li>
								<li><%= link_to "Logout", logout_path %></li>
							</ul>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>
		
	<div class="container">
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
				<a class="close" data-dismiss="alert">×</a>
				<%= msg %>
			</div>
		<% end %>
		<div id="content" class="row">
			<div class="span12">
				<%= content_tag :h1, yield(:title) if show_title? %>
				<%= yield %>
			</div>
		</div>
		<div id="footer" class="row">
				<div class="span2">
					<a href="http://newhopeinitiative.org">NHI Home</a>
				</div>
				<div class="span2">
					<a href="https://github.com/buckolas/NewHopeInitiative/wiki/FAQ">FAQ</a>
				</div>
				<div class="span2">
					<a href="https://github.com/buckolas/NewHopeInitiative/issues">Request Changes</a>
				</div>
				<div class="span2">
					<a href="https://github.com/buckolas/NewHopeInitiative">GitHub Project</a>
				</div>
		</div>
	</div>
	
  </body>
</html>